name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Set up environment variables for tags
    - name: Set up Docker tags
      run: |
        echo "DOCKER_TAG_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "DOCKER_TAG_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV

    # Build the Docker image with multiple tags
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/story-craft:latest \
                     -t ${{ secrets.DOCKER_USERNAME }}/story-craft:${{ env.DOCKER_TAG_RUN_ID }} story-craft

    # Push all Docker image tags to DockerHub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/story-craft:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/story-craft:${{ env.DOCKER_TAG_RUN_ID }}
